# -*- coding: utf-8 -*-
"""streamlitWorkout.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JrIRm4rO_lYgOkJMqlC17E5X7lwqFGBT
"""

!pip install --upgrade streamlit

!wget -q -O - ipv4.icanhazip.com

!streamlit run workout.py & npx  localtunnel --port 8501

